### ISSUE TITLE
RECoders.org gives a malicious/misleading redirection

### ISSUE THREAD

**Issue by jmazzola** [contra/JMD#14]
I'd recommend removing that inside of your source code.

**Comment by contra** [comment]
Where is it in the code? Feel free to send a PR removing it.

**Comment by jmazzola** [comment]
It's located here:
https://github.com/contra/JMD/blob/master/jmd-cli/src/main/java/net/contra/jmd/Deobfuscator.java#L27

Do you have an updated link in that you post information/updates on this project or is this Github the new place for that? Thanks :)

**Comment by contra** [comment]
@jmazzola URL should be github, don't really mess w/ forums anymore

**Comment by kidoz** [comment]
Done
