### ISSUE TITLE
Unable to Deobfuscate Allatori

### ISSUE THREAD

**Issue by biepie70** [contra/JMD#18]
I am unable to deobfuscate a file that suggests it is obfuscated using allatori obfuscator. 
![jmd](https://user-images.githubusercontent.com/22099619/51013084-b05aff80-1588-11e9-9e3c-ddd0c59429a5.JPG)

Can anyone please deobfuscate the file for me. Also it is malicious so please use a VM. I need to analyze the file. Here is the link to the file.
[https://ufile.io/lmx3b](url)

**Comment by kidoz** [comment]
Hi! I try to help you.
